INSERT INTO tasks_task (user_id, title, description, status, priority, created_at, updated_at) VALUES
(1, 'Organizar arquivos', 'Organizar e classificar documentos do projeto', 'PENDING', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Enviar relatório mensal', 'Preparar e enviar relatório financeiro do mês', 'PENDING', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'Revisar contrato', 'Ler cláusulas e apontar dúvidas jurídicas', 'PENDING', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'Planejar reunião', 'Definir pauta e enviar convite para participantes', 'COMPLETED', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'Atualizar website', 'Corrigir texto da página inicial e imagens', 'PENDING', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'Testes unitários', 'Escrever e rodar testes nas novas funções', 'PENDING', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'Backup de banco', 'Gerar backup completo e validar integridade', 'COMPLETED', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 'Onboarding novo colega', 'Configurar acesso e apresentar processos', 'PENDING', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 'Pesquisar fornecedor', 'Comparar preços e prazos de entrega', 'PENDING', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 'Ajustar layout', 'Ajustes no CSS para responsividade mobile', 'PENDING', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, 'Enviar faturas', 'Conferir valores e enviar faturas aos clientes', 'COMPLETED', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 'Limpar base de dados', 'Remover registros duplicados e inconsistentes', 'PENDING', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(13, 'Criar documentação', 'Documentar API e endpoints principais', 'PENDING', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(14, 'Reunião com marketing', 'Alinhar campanha de lançamento', 'COMPLETED', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(15, 'Melhorar SEO', 'Rever meta tags e conteúdos para palavras-chave', 'PENDING', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(16, 'Auditoria interna', 'Verificar conformidade com processos internos', 'PENDING', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(17, 'Configurar CI/CD', 'Automatizar deploy para ambiente de testes', 'PENDING', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(18, 'Responder clientes', 'Responder tickets abertos na última semana', 'COMPLETED', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(19, 'Mapear jornada do usuário', 'Criar fluxos e identificar pontos de melhoria', 'PENDING', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(20, 'Comprar materiais', 'Solicitar orçamentos e efetuar compras necessárias', 'PENDING', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(21, 'Refatorar função X', 'Simplificar lógica e adicionar comentários', 'PENDING', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(22, 'Treinamento equipe', 'Preparar slides e exercícios práticos', 'COMPLETED', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(23, 'Testar integração', 'Validar integração entre serviços externos', 'PENDING', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(24, 'Criar wireframes', 'Desenhar telas iniciais para nova funcionalidade', 'PENDING', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(25, 'Configurar alerta', 'Criar monitoramento e alertas para CPU', 'PENDING', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(26, 'Revisar políticas', 'Atualizar políticas internas de segurança', 'PENDING', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(27, 'Organizar evento', 'Reservar local e confirmar palestrantes', 'PENDING', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(28, 'Migrar dados', 'Planejar e executar migração para novo esquema', 'PENDING', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(29, 'Analisar métricas', 'Gerar relatório de conversão e retenção', 'COMPLETED', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(30, 'Corrigir bug crítico', 'Investigar erro em produção e aplicar correção', 'COMPLETED', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
(1, 'Planejar sprint', 'Definir backlog e estimativas para a próxima sprint', 'PENDING', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'Corrigir bug A', 'Investigar e corrigir exceção no módulo de pagamentos', 'COMPLETED', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'Revisar PRs', 'Revisar pull requests abertos no repositório principal', 'PENDING', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'Atualizar dependências', 'Subir versões de bibliotecas e testar compatibilidade', 'PENDING', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'Documentar endpoint', 'Adicionar exemplos de uso na documentação da API', 'PENDING', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'Reunião com cliente', 'Apresentar roadmap e coletar feedback', 'COMPLETED', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'Aprimorar logs', 'Adicionar contexto e níveis apropriados aos logs', 'PENDING', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'Otimizar consulta', 'Reduzir tempo de resposta da consulta de relatórios', 'PENDING', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'Configurar monitoramento', 'Criar dashboards para métricas críticas', 'PENDING', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'Testes de carga', 'Executar testes de performance no ambiente de staging', 'PENDING', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'Refinar UX', 'Coletar feedback e ajustar fluxo de cadastro', 'COMPLETED', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'Revisar políticas de segurança', 'Verificar requisitos de criptografia e acesso', 'PENDING', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(2, 'Criar protótipo', 'Desenvolver protótipo de nova tela de vendas', 'PENDING', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Ajustar integrações', 'Corrigir timeouts nas integrações externas', 'PENDING', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Implementar caching', 'Adicionar cache em endpoints com alto tráfego', 'PENDING', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Validar requisitos', 'Confirmar requisitos com stakeholder', 'COMPLETED', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Atualizar README', 'Documentar passos de setup para novos desenvolvedores', 'PENDING', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Automatizar builds', 'Criar pipeline para builds automáticos', 'PENDING', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Revisar contratos', 'Analisar termos com o jurídico', 'PENDING', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Testar regressão', 'Executar suíte de testes após última release', 'COMPLETED', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Mapear releases', 'Planejar releases mensais e dependências', 'PENDING', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Pesquisar soluções', 'Avaliar provedores para armazenamento de arquivos', 'PENDING', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Corrigir formulário', 'Ajustar validações e mensagens de erro', 'PENDING', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Preparar demo', 'Montar demo para apresentação executiva', 'COMPLETED', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(3, 'Criar testes E2E', 'Escrever cenários de ponta a ponta para fluxo crítico', 'PENDING', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'Aprimorar CSS', 'Corrigir estilos quebrados em navegadores antigos', 'PENDING', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'Reunir métricas', 'Coletar dados de uso para análise trimestral', 'COMPLETED', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'Planejar campanha', 'Definir público e mensagens para campanha digital', 'PENDING', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'Ajustar permissão', 'Corrigir escopo de permissões de API', 'PENDING', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'Gerar relatórios', 'Implementar exportação de relatórios em CSV', 'PENDING', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'Revisar onboarding', 'Melhorar textos e passos do onboarding', 'COMPLETED', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'Corrigir layout mobile', 'Alinhar componentes em telas pequenas', 'PENDING', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'Validar formulário', 'Garantir máscara e validações de CPF/CNPJ', 'PENDING', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'Monitorar filas', 'Verificar processamento de filas assíncronas', 'PENDING', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'Configurar SSL', 'Renovar certificado e configurar auto-renew', 'COMPLETED', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'Ajuste de permissões', 'Revisar papéis e permissões internas', 'PENDING', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(4, 'Organizar backlog', 'Priorizar demandas e limpar itens antigos', 'PENDING', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'Atualizar templates', 'Padronizar templates de e-mail', 'PENDING', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'Implementar webhooks', 'Criar endpoints para notificações externas', 'PENDING', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'Testar rollback', 'Validar procedimentos de rollback em deploy', 'PENDING', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'Criar script de migração', 'Script SQL para migrar esquema X para Y', 'PENDING', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'Revisar custos', 'Analisar custos de infraestrutura na nuvem', 'COMPLETED', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'Configurar alertas de erro', 'Notificações via Slack para erros críticos', 'PENDING', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'Ajustar CORS', 'Habilitar origens necessárias para integração', 'PENDING', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'Criar formulário', 'Novo formulário para coleta de feedback', 'COMPLETED', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'Estudar biblioteca', 'Avaliar biblioteca para gráficos interativos', 'PENDING', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'Corrigir race condition', 'Investigar condição de corrida em processamento paralelo', 'PENDING', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'Preparar release notes', 'Escrever notas de versão para última entrega', 'COMPLETED', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(5, 'Auditar logs', 'Analisar logs de erros dos últimos 30 dias', 'PENDING', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'Melhorar cache', 'Aprimorar políticas de expiração do cache', 'PENDING', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'Testar API pública', 'Verificar endpoints públicos de terceiros', 'COMPLETED', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'Criar diagramas', 'Desenhar arquitetura da nova feature', 'PENDING', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'Enviar comunicação', 'Informar clientes sobre manutenção programada', 'PENDING', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'Revisar SLA', 'Ajustar acordos de nível de serviço com parceiros', 'PENDING', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'Corrigir Timeout', 'Aumentar timeout em chamadas demoradas', 'PENDING', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'Implementar retry', 'Adicionar lógica de retry em integrações instáveis', 'PENDING', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'Testes de usabilidade', 'Conduzir testes com usuários reais', 'COMPLETED', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'Organizar servidores', 'Limpeza e reorganização de instâncias antigas', 'PENDING', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'Atualizar DNS', 'Alterar registros para nova CDN', 'COMPLETED', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'Planejar roadmap', 'Definir milestones para próximos 6 meses', 'PENDING', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
